# Generated by Django 5.1.5 on 2025-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_emailtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.CharField(choices=[('minutely', 'Minutely'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
