# Generated by Django 5.2 on 2025-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_repeat_interval_task_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtask',
            name='repeat',
            field=models.CharField(choices=[('none', 'No Repeat'), ('minutely', 'Every Minute'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10),
        ),
    ]
